version: "3"
services:
  kafka01:
    image: confluentinc/cp-kafka:7.7.0
    ports:
      # ホストとの通信に使う9092だけをexposeする（29092はbroker間の通信のみに使うので、exposeしない）
      - 9092:9092
    environment:
      # KRaft modeで動かす（zookeeper modeは最新のkafkaでは非推奨っぽい？）
      KAFKA_NODE_ID: 1
      # LISTNER_HOSTはホストとの通信用、LISTENER_INTERNALはdocker内通信用
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT,LISTENER_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://kafka01:29092,LISTENER_HOST://localhost:9092'
      # 各nodeはbrokerかつcontrollerとしてふるまう
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:29093,2@kafka02:29093,3@kafka03:29093'
      # kafkaがlistenするポートを記載する（LISTNER_HOSTはlocalhost外からlistenするのでhostnameを指定しない）
      KAFKA_LISTENERS: 'CONTROLLER://kafka01:29093,LISTENER_INTERNAL://kafka01:29092,LISTENER_HOST://:9092'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      # 同じclusterに参加するnodeはすべて同じにする
      CLUSTER_ID: f4H3lfJOQwy-B--Pc2-j_w
  kafka02:
    image: confluentinc/cp-kafka:7.7.0
    ports:
      - 9093:9093
    environment:
      KAFKA_NODE_ID: 2
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT,LISTENER_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://kafka02:29092,LISTENER_HOST://localhost:9093'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:29093,2@kafka02:29093,3@kafka03:29093'
      KAFKA_LISTENERS: 'CONTROLLER://kafka02:29093,LISTENER_INTERNAL://kafka02:29092,LISTENER_HOST://:9093'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      CLUSTER_ID: f4H3lfJOQwy-B--Pc2-j_w
  kafka03:
    image: confluentinc/cp-kafka:7.7.0
    ports:
      - 9094:9094
    environment:
      KAFKA_NODE_ID: 3
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: 'CONTROLLER:PLAINTEXT,LISTENER_INTERNAL:PLAINTEXT,LISTENER_HOST:PLAINTEXT'
      KAFKA_ADVERTISED_LISTENERS: 'LISTENER_INTERNAL://kafka03:29092,LISTENER_HOST://localhost:9094'
      KAFKA_PROCESS_ROLES: 'broker,controller'
      KAFKA_CONTROLLER_QUORUM_VOTERS: '1@kafka01:29093,2@kafka02:29093,3@kafka03:29093'
      KAFKA_LISTENERS: 'CONTROLLER://kafka03:29093,LISTENER_INTERNAL://kafka03:29092,LISTENER_HOST://:9094'
      KAFKA_CONTROLLER_LISTENER_NAMES: 'CONTROLLER'
      KAFKA_INTER_BROKER_LISTENER_NAME: 'LISTENER_INTERNAL'
      CLUSTER_ID: f4H3lfJOQwy-B--Pc2-j_w
  control-center:
    image: confluentinc/cp-enterprise-control-center:7.7.0
    depends_on:
      - kafka01
      - kafka02
      - kafka03
    ports:
      - 9021:9021
    environment:
      CONTROL_CENTER_BOOTSTRAP_SERVERS: kafka01:29092,kafka02:29092,kafka03:29092
      CONTROL_CENTER_REPLICATION_FACTOR: 3
      PORT: 9021
